export type ThemeTokens = { background: string; surface: string; text: string; muted: string; primary: string };
export type Product = { number: number; category: string; name: string; variant: string; description: string; price: number; unit: string; photoUrls: string[]; stockOut: boolean; hide: boolean };
export type ShowcaseConfig = {
  slug: string;
  title?: string;
  subtitle?: string;
  companyAddress?: string;
  companyEmail?: string;
  companyPhone?: string;
  contactPersonName?: string;
  contactPersonEmail?: string;
  contactPersonPhone?: string;
  contactPersonWhatsapp?: string;
  headline?: string;
  content?: string;
  image?: string;
  instagram?: string;
  facebook?: string;
  twitterX?: string;
  tokopedia?: string;
  tiktok?: string;
  shopee?: string;
  lazada?: string;
  others?: string[];
  owner: { name: string; handle: string };
  showcase: { title: string; category: string; description: string; badge: string };
  hero: { eyebrow: string; title: string; description: string; primaryAction: string; secondaryAction: string };
  products: Product[];
  theme: { light: ThemeTokens; dark: ThemeTokens };
};
