import config from './config.json';
import './example2.css';
import { Aurora } from '../../components/react-bits/Aurora';
import { BlurText } from '../../components/react-bits/BlurText';
import { ShowcaseCatalog } from '../../components/ShowcaseCatalog';
import { ShowcaseInfo } from '../../components/ShowcaseInfo';
import type { ShowcaseConfig } from '../../types/showcase';
import { useTheme } from '../../hooks/useTheme';
const data = config as ShowcaseConfig;
export default function Example2({ navigate }: { navigate: (path: string) => void }) { const { theme } = useTheme(); const tokens = data.theme[theme]; return <main className="store netlify-page" style={{ '--bg': tokens.background, '--surface': tokens.surface, '--text': tokens.text, '--muted': tokens.muted, '--primary': tokens.primary } as React.CSSProperties}><section className="netlify-hero"><Aurora /><header className="netlify-topbar"><button onClick={() => navigate('/')} className="netlify-wordmark">{data.title || data.showcase.title}</button><button className="netlify-outline" onClick={() => document.getElementById('contact')?.scrollIntoView({ behavior: 'smooth' })}>{data.contactPersonName || data.owner.name}</button></header><div className="netlify-hero-inner"><p className="eyebrow">{data.hero.eyebrow}</p><h1><BlurText>{data.headline || data.title || data.showcase.title}</BlurText></h1><p>{data.content || data.subtitle || data.showcase.description}</p><button className="netlify-cta" onClick={() => document.getElementById('catalog')?.scrollIntoView({ behavior: 'smooth' })}>{data.hero.primaryAction} ↗</button><div className="netlify-status" aria-label={`${data.owner.handle} ${data.showcase.category}`}><div className="netlify-status-top"><span className="netlify-status-dots"><i /><i /><i /></span><span>{data.showcase.badge}</span></div><strong>{data.owner.handle}</strong><span>{data.showcase.category}</span><small>{data.companyEmail || data.companyAddress || data.subtitle || ''}</small></div></div></section><section className="netlify-library" id="catalog"><div className="netlify-section-title"><p className="eyebrow">{data.showcase.category}</p><h2>{data.subtitle || data.showcase.description}</h2><button className="netlify-link" onClick={() => document.getElementById('contact')?.scrollIntoView({ behavior: 'smooth' })}>{data.hero.secondaryAction} ↗</button></div><ShowcaseCatalog products={data.products} slug={data.slug} navigate={navigate} whatsapp={data.contactPersonWhatsapp} purchaseLabel={data.hero.primaryAction} detailLabel={data.hero.secondaryAction} variant="masonry" /></section><ShowcaseInfo config={data} /></main>; }
